### ISSUE TITLE
Issues with colspan (.txt output) and shading (.html, .pdf outputs) when trying to convert a figure to a table

### ISSUE THREAD

**Issue by lbartholomew-rpc** [ietf-tools/xml2rfc#833] opened 2022-07-14 23:00 UTC
Issues with colspan (.txt output) and shading (.html, .pdf outputs) when trying to convert a figure to a table (Table 1 in the "-with-Table1" files listed below).

The "colspan" entries had several undesirable carriage returns each in the .txt output (the "BIFT indices for Packets with SI=0" and "BIFT indices for BitString/Packet with SI=1" rows).

Please see

https://www.rfc-editor.org/v3test/draft-ietf-bier-te-arch-13-with-Table1.xml
https://www.rfc-editor.org/v3test/draft-ietf-bier-te-arch-13-with-Table1.txt
https://www.rfc-editor.org/v3test/draft-ietf-bier-te-arch-13-with-Table1.html
https://www.rfc-editor.org/v3test/draft-ietf-bier-te-arch-13-with-Table1.pdf

The shading in the 4th row in the .html and .pdf outputs was off, but no carriage-return issue for the colspan entries.

To see what the correct layout should be, please see Figure 4 in

https://www.rfc-editor.org/v3test/draft-ietf-bier-te-arch-13-xml2.xml
https://www.rfc-editor.org/v3test/draft-ietf-bier-te-arch-13-xml2.txt

**Comment by alicerusso** [comment] 2022-07-25 21:41
Seems to be another example of the colspan issue.  Attempting to use `<table>` to create Table 5 in this document: https://www.ietf.org/id/draft-irtf-nmrg-ibn-intent-classification-08.txt
In the text output, see the 5 right-most columns --`<th>` is being forced into one column even though it has colspan set greater than 1 (e.g., `<th colspan="6">Intent Scope</th>`). 

Files:
https://www.rfc-editor.org/v3test/colspan-table-example.xml
https://www.rfc-editor.org/v3test/colspan-table-example.txt
https://www.rfc-editor.org/v3test/colspan-table-example.html
https://www.rfc-editor.org/v3test/colspan-table-example.pdf

original:
```
   +---------+-------------+-----------------+-----+-----+-----+-----+
   |Intent   | Intent      | Intent          | DCN | DCN | ABS | L-C |
   |User     | Type        | Scope           | Res | Net |     |     |
   |         |             +-----------------+-----+-----+-----+-----+
   |         |             |C1|C2|C3|C4|C5|C6|C1|C2|C1|C2|C1|C2|C1|C2|
   +---------+-------------+--+--+--+--+--+--+--+--+--+--+--+--+--+--+
```

partial text output:
``` 
   +===========+=============+=================+=====+=====+=====+=====+
   |Intent User| Intent Type |In               |DC   |DC   |AB   |L-   |
   |           |             |te               |N    |N    |S    |C    |
   |           |             |nt               |Re   |Ne   |     |     |
   |           |             |Sc               |s    |t    |     |     |
   |           |             |op               |     |     |     |     |
   |           |             |e                |     |     |     |     |
   |           |             +==+==+==+==+==+==+==+==+==+==+==+==+==+==+
   |           |             |C1|C2|C3|C4|C5|C6|C1|C2|C1|C2|C1|C2|C1|C2|
   +===========+=============+==+==+==+==+==+==+==+==+==+==+==+==+==+==+
```

**Comment by kesara** [comment] 2022-08-31 07:24
#886 is a fix for the table colspan issue in text format.
Generated table for the above example is as follows:
```
   +===========+=============+=================+=====+=====+=====+=====+
   |Intent User| Intent Type |Intent           |DCN  |DCN  |ABS  |L-C  |
   |           |             |Scope            |Res  |Net  |     |     |
   |           |             +==+==+==+==+==+==+==+==+==+==+==+==+==+==+
   |           |             |C1|C2|C3|C4|C5|C6|C1|C2|C1|C2|C1|C2|C1|C2|
   +===========+=============+==+==+==+==+==+==+==+==+==+==+==+==+==+==+
```

**Comment by lbartholomew-rpc** [comment] 2022-10-10 18:23
Hi, kesara.  I don't see the fix implemented yet.  Which version of xml2rfc will implement it?  We have 3.15.0.  Thanks!

**Comment by kesara** [comment] 2022-10-10 19:01
@lbartholomew-rpc, My bad. There are two issues separate issues.
3.15.0 should have the fix for the table column issue in https://github.com/ietf-tools/xml2rfc/issues/833#issuecomment-1194666542
Can you confirm?
HTML shading issue is not fixed yet.
I think the examples in https://github.com/ietf-tools/xml2rfc/issues/833#issue-1305368164 are stale now.

**Comment by kesara** [comment] 2022-10-10 21:27
@lbartholomew-rpc, looks like GitHub doesn't post attachments from email replies.
Can you attach the draft-ietf-bier-te-arch-13-with-Table1-10Oct2022_Issue-833.txt to this issue?

> Guessing that you're talking about the "colspan-table-example" part of the ticket instead?  If yes, I'll ask Alice Russo to verify that one.

Yes.

**Comment by lbartholomew-rpc** [comment] 2022-10-10 21:51
Hi, @kesara.  Here's that snapshot from earlier today (same issue as the one I'd reported initially).  Thank you, & sorry for trying the email route.
<img width="572" alt="Screen Shot 2022-10-10 at 1 13 33 PM" src="https://user-images.githubusercontent.com/40249182/194957714-818beaec-ec04-4b1a-b830-9f033143c1ab.png">

**Comment by alicerusso** [comment] 2022-10-18 20:28
> Re: 3.15.0 should have the fix for the table column issue in https://github.com/ietf-tools/xml2rfc/issues/833#issuecomment-1194666542
> Can you confirm?

Confirmed (re: `<th colspan="6">Intent Scope</th>`).

However, as @lbartholomew-rpc pointed out in https://github.com/ietf-tools/xml2rfc/issues/833#issuecomment-1273849967, the original input file ([draft-ietf-bier-te-arch-13-with-Table1.xml](https://www.rfc-editor.org/v3test/draft-ietf-bier-te-arch-13-with-Table1.xml)) still has the issue in the TXT output where each word of this `<td>` appears on its own line:
`<td colspan="3" align="center">BIFT indices for Packets with SI=0</td>` (and the same issue when align="left")

**Comment by kesara** [comment] 2023-09-06 08:02
I'm closing this ticket as it's not possible to find a good solution for the shading issue with `colspan` in CSS. Any additional elements that can be introduced to fix a simple `colspan` shading will fail with complex cases where there are multiple `colspan` values in a single row.

Other issues in this ticket are solved.

**Closed by kesara** 2023-09-06 08:02 UTC
Labels: bug, accepted, text, html, pdf
