### ISSUE TITLE
weird formatting in plain text index

### ISSUE THREAD

**Issue by reschke** [ietf-tools/xml2rfc#785] opened 2022-05-29 06:39 UTC
For instance:

~~~
            Date  *_Section 6.6.1_*
            ETag  *_Section 8.8.3_*
            Expect  *_Section 10.1.1_*
            From  *_Section 10.1.2_*
            Host  *_Section 7.2_*
            If-Match  *_Section 13.1.1_*
~~~

I *believe* this was introduced recently, and not on purpose...

**Comment by cabo** [comment] 2022-05-29 08:15
It was fully on purpose. 

The ping was to get this right in the html/pdf version. As usual, the plaintext version suffers a bit.

**Comment by cabo** [comment] 2022-05-29 09:05
Adding link: https://github.com/ietf-tools/xml2rfc/issues/756

The problem is that index generation is done in the prep tool, not renderer specific.
See <https://mailarchive.ietf.org/arch/msg/rfc-markdown/7JCbdtG8xISqHMdmJmAoXPn0EhM> and the thread around it for a discussion why we need renderer-specific tweaks.

More important than the detailed way of indicating the primary reference is the way we handle a plethora of non-primary ones: see https://www.rfc-editor.org/rfc/authors/rfc9114.html#name-index for an example.  Section/Paragraph need to become § and ¶; multiple namings in one paragraph, or multiple paragraphs in one section, need to be consolidated.

**Comment by kesara** [comment] 2022-06-06 21:56
I am closing this as not an issue.

**Closed by kesara** 2022-06-06 21:56 UTC
