### ISSUE TITLE
https://github.com/ietf-tools/xml2rfc/issues => Text. Been waiting for 10 min without results.

### ISSUE THREAD

**Issue by bclaise** [ietf-tools/xml2rfc#885] opened 2022-08-29 21:26 UTC
### Describe the issue

Hi, 

I tried to go from xml to txt for my private (slighty modified) copy of https://github.com/bclaise/draft-tgraf-opsawg-ipfix-srv6-srh/blob/main/draft-tgraf-opsawg-ipfix-srv6-srh-06.xml
About 12 minutes now, and not a single answer from the tool.
It was working better (not great) before. 
I notice it goes faster if I re-select my file from "Browse", even if it was already selected.

B.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by bclaise** [comment] 2022-08-29 21:27
And when the answer arrives ...

<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.19.8</center>
</body>
</html>

**Comment by rjsparks** [comment] 2022-08-29 22:23
Benoit - please provide more context - I _think_ you are saying you are running into this timeout at author-tools.ietf.org. If that's not the case, please clarify.

**Comment by kesara** [comment] 2022-08-29 23:08
Including `.xml` extension in the references should fix the issues for now.
Example: `<?rfc include='reference.RFC.2119.xml'?>`.

This _could be_ an `xml2rfc` issue, because `xml2rfc` should allow citation includes without extension for v2 schema.

**Comment by cabo** [comment] 2022-08-29 23:24
> for v2 schema

I'm not quite sure what you mean by that -- the PI include mechanism is wholesale v2, so it always should support v2 features.

**Comment by kesara** [comment] 2022-08-29 23:48
Original draft works fine with `xml2rfc --v2` switch and `xml2rfc --v2v3` switch.
And the original draft also works on author tools without any modifications because author tools run v2v3 conversion for v2 drafts.

I think the earlier issue that @bclaise had was due to an SSL certificate issue with redirections, which has been corrected.

Closing this issue because I think this is the expected behaviour.

**Closed by kesara** 2022-08-29 23:48 UTC
Labels: bug
