### ISSUE TITLE
Some tables within `<dd>` overlap text in pdf output

### ISSUE THREAD

**Issue by rvanrheenen** [ietf-tools/xml2rfc#1117] opened 2024-03-21 19:25 UTC
### Describe the issue

Tables 3 and 6 overlap the text that precedes them in the pdf output (these tables looks fine in the txt and html). 

These tables appear in `<dd>` within `<dl>`, but Tables 1-35 are tagged the same way and do not have this issue. Note that spacing="compact" is used for the `<dl>`. 

The overlap does not occur if the `<dl>` is updated to include newline="true", but this changes the appearance of the entire list.

Files:
https://www.rfc-editor.org/v3test/rfc9559-TEST.xml
https://www.rfc-editor.org/v3test/rfc9559-TEST.txt
https://www.rfc-editor.org/v3test/rfc9559-TEST.html
https://www.rfc-editor.org/v3test/rfc9559-TEST.pdf

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ajeanmahoney** [comment] 2024-03-22 00:11
See also https://github.com/ietf-tools/xml2rfc/issues/1086

**Comment by rvanrheenen** [comment] 2024-03-22 01:41
Also see #1118 and #1086 (other issues re `<table>` in `<dl>` found in same document)

**Comment by kesara** [comment] 2024-03-25 21:46
Duplicate of #1086

**Comment by rvanrheenen** [comment] 2024-03-25 23:17
@kesara I'd like to clarify that this issue is different from #1086.

This issue affects **only Tables 3 and 6** of the pdf output. They cover part of the text preceding them so you can't see it. This doesn't occur in other tables in the doc that are tagged the same way, and this does not occur in the txt or html outputs.

#1086 also deals with spacing, but not this particular thing.

**Comment by kesara** [comment] 2024-03-26 00:28
@rvanrheenen I thought #1086 covers the same issue but also requests more. Also Table 6 in the example has the same issue.
Reopening this as this is a more targeted bug report.

**Comment by rvanrheenen** [comment] 2024-03-26 18:21
@kesara thank you! Yes, I examined each table in the test files, and only Table 3 and Table 6 have this issue. Thank you!

**Closed** 2024-04-05 21:17 UTC
Labels: bug, pdf
